# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "hello-dependent"
version = "0.0.0"
name = "Buildpack (dependent) Template"
homepage = "https://github.com/mattmoor/hello-dependencies"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"
